# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60b1e8620579702f629e4df98fa325ce70ce709a7632c63d73b5788ae2629e2264ea866cffdb39fafe1b10762f5d895f6a0db8fc052579595d061904e124d9f7

test:
  secret_key_base: 2e3eab49ce9787d1393a533aef9d5ad15c8aca60e952ddfec2422226c45bf2e3aa90c84d101f6b8b50e393efb32419df53d27e77a51e878c41d82141f6a1f405

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
